"""Generates ../light-panel.yaml: 8 touch tiles (4 x 2) for HA lights/switches.

The eight tiles are identical apart from their number, so they're generated
from one template here rather than hand-copied. Which entity, name and icon
each tile shows is NOT set here: that's per device, in the device file's
substitutions (b1_entity, b1_name, b1_icon ... b8_*).

Run from anywhere:  python projects/light-panel/tools/gen_light_panel.py

  --demo   also write tools/demo/light-panel-demo.yaml: the same project, but
           each tap toggles its tile locally (no HA needed), for testing the
           layout and touch calibration on a bare board.
"""
import sys
from pathlib import Path

from icon_set import ICON_SET

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "light-panel.yaml"
DEMO_OUT = HERE.parents[2] / "tools" / "demo" / "light-panel-demo.yaml"
TILES = 8
DEMO = "--demo" in sys.argv

# ---- icon catalogue for the font -------------------------------------------
codepoints = [cp for _, icons in ICON_SET for _, cp in icons]
assert len(codepoints) == len(set(codepoints)), "duplicate icon in ICON_SET"
glyph_lines = []
for group, icons in ICON_SET:
    glyph_lines.append(f"      # --- {group} ---")
    for name, cp in icons:
        glyph_lines.append(f'      - "\\U000{cp}"   # {cp}  mdi:{name}')
glyph_list = "\n".join(glyph_lines)

# ---- per-tile state sensors -------------------------------------------------
texts = "\n".join(
    f"""  - platform: homeassistant
    id: st{i}
    entity_id: ${{b{i}_entity}}
    internal: true
    on_value:
      - lvgl.widget.update:
          id: btn{i}
          state:
            checked: !lambda 'return x == "on";'
            disabled: !lambda 'return x != "on" && x != "off";'"""
    for i in range(1, TILES + 1)
)

# ---- tiles ------------------------------------------------------------------
widgets = []
for i in range(1, TILES + 1):
    col, row = (i - 1) % 4, (i - 1) // 4
    widgets.append(f"""        - button:
            id: btn{i}
            styles: tile
            x: {4 + col * 79}
            y: {4 + row * 118}
            width: 75
            height: 114
            state:
              disabled: true           # until HA reports the state
            pressed:
              bg_color: 0x3A3A3A
            checked:                   # entity is on
              bg_color: 0xF59E0B
              text_color: 0x1A1A1A
            disabled:                  # entity unavailable
              bg_color: 0x141414
              text_color: 0x4A4A4A
              border_width: 2
              border_color: 0x7F1D1D
            on_click:
              - logger.log: {{format: "Tapped ${{b{i}_name}}", level: INFO}}
              - homeassistant.action:
                  action: homeassistant.toggle
                  data:
                    entity_id: ${{b{i}_entity}}
            widgets:
              - label:
                  align: TOP_MID
                  y: 16
                  text_font: font_icons
                  text: "${{b{i}_icon}}"
              - label:
                  align: BOTTOM_MID
                  y: -10
                  width: 71
                  height: 20
                  long_mode: DOT
                  text_align: CENTER
                  text: "${{b{i}_name}}\"""")
widgets = "\n".join(widgets)

yaml = f"""# =============================================================================
#  Project: light panel  (GENERATED by tools/gen_light_panel.py; edit that)
#  8 touch tiles (4 x 2) that toggle Home Assistant lights and switches.
#  Needs: a 320x240 landscape LVGL display (`tft`) with a calibrated
#  touchscreen `touch`, light `backlight`.
#
#  Tap a tile to toggle it (any light or switch). Tiles show the real state:
#    amber tile        on
#    dark tile         off
#    faded, red edge   HA says it is unavailable (tap does nothing)
#  A red banner appears if the panel loses its connection to HA.
#
#  The screen goes off after "Screen timeout" (set in HA, default 60 s).
#  While it's off, the first tap only wakes it, so you can't switch a light
#  by accident in the dark.
#
#  The device file sets each tile with three substitutions, b1..b8:
#    bN_entity   e.g. light.kitchen_light (any entity that can toggle)
#    bN_name     about 9 characters max
#    bN_icon     one of the 100 codes listed under `font:` below,
#                e.g. "\\U000F0769" for mdi:ceiling-light
#  Tiles: b1-b4 top row left to right, b5-b8 bottom row.
#
#  HA side: in the ESPHome integration's options for the device, turn on
#  "Allow the device to perform Home Assistant actions", or taps do nothing.
# =============================================================================

esphome:
  on_boot:
    priority: -100
    then:
      - script.execute: show_connection

api:
  on_client_connected:
    - script.execute: show_connection
  on_client_disconnected:
    - script.execute: show_connection

touchscreen:
  - id: !extend touch
    on_touch:
      - logger.log:
          format: "touch x=%d y=%d raw=%d,%d"
          args: [touch.x, touch.y, touch.x_raw, touch.y_raw]
          level: INFO
    on_release:
      # While the screen is off LVGL is paused and ignores touches, so this
      # tap only wakes the screen.
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on: backlight

light:
  # Awake brightness: set it from HA with the Backlight light.
  - id: !extend backlight
    default_transition_length: 0.3s

number:
  - platform: template
    id: screen_timeout
    name: Screen timeout
    icon: mdi:timer-outline
    unit_of_measurement: s
    min_value: 10
    max_value: 600
    step: 10
    initial_value: 60
    optimistic: true
    restore_value: true
    entity_category: config

# =============================================================================
#  Entity states from Home Assistant: "on", "off", "unavailable", ...
# =============================================================================
text_sensor:
{texts}

# =============================================================================
#  Connection banner
# =============================================================================
script:
  - id: show_connection
    then:
      - lambda: |-
          bool ok = ${{ha_connected}};   // from common/base.yaml
          if (ok) lv_obj_add_flag(id(banner_offline), LV_OBJ_FLAG_HIDDEN);
          else lv_obj_remove_flag(id(banner_offline), LV_OBJ_FLAG_HIDDEN);

interval:
  - interval: 5s
    then:
      - script.execute: show_connection

# =============================================================================
#  Fonts
# =============================================================================
font:
  # Material Design Icons: a fixed set of 100 for a typical home (from
  # tools/icon_set.py). Any tile can use any icon listed here, and tiles can
  # share icons. An icon that isn't listed shows as a blank tile: add it to
  # tools/icon_set.py and regenerate (each code only once, or Validate fails
  # with "Found duplicate glyphs").
  - file:
      type: web
      url: https://cdn.jsdelivr.net/npm/@mdi/font@7.4.47/fonts/materialdesignicons-webfont.ttf
    id: font_icons
    size: 56
    bpp: 4
    glyphs:
{glyph_list}
  - file: {{type: gfonts, family: Roboto, weight: 500}}
    id: font_name
    size: 16
    bpp: 4
  - file: {{type: gfonts, family: Roboto, weight: 700}}
    id: font_banner
    size: 18
    bpp: 4

# =============================================================================
#  Layout (LVGL)
# =============================================================================
lvgl:
  displays: tft
  rotation: 90             # landscape, USB sockets on the right
  buffer_size: 25%
  default_font: font_name
  # Screen off after the timeout. LVGL pauses, so the next tap only wakes it.
  on_idle:
    timeout: !lambda "return (uint32_t) (id(screen_timeout).state * 1000);"
    then:
      - light.turn_off: backlight
      - lvgl.pause:
  style_definitions:
    # Icon and name inherit text_color from the tile, so they follow its state.
    - id: tile
      radius: 10
      border_width: 0
      pad_all: 0
      shadow_width: 0
      bg_color: 0x1E1E1E
      text_color: 0x9A9A9A
  pages:
    - id: main_page
      bg_color: 0x000000
      scrollable: false
      pad_all: 0
      widgets:
{widgets}
        - label:
            id: banner_offline
            align: CENTER
            text: "Not connected to Home Assistant"
            text_font: font_banner
            text_color: 0xFFFFFF
            bg_color: 0xB91C1C
            bg_opa: COVER
            radius: 6
            pad_all: 8
"""

OUT.write_text(yaml, encoding="utf-8")
print(f"written {OUT} ({yaml.count(chr(10))} lines)")

if DEMO:
    # Same project, but tiles start enabled and toggle themselves on tap.
    initial_state = """            state:
              disabled: true           # until HA reports the state
"""
    assert yaml.count(initial_state) == TILES
    demo = yaml.replace(initial_state, "            checkable: true            # DEMO: toggles locally\n")
    demo = demo.replace(
        "#  Project: light panel  (GENERATED by tools/gen_light_panel.py; edit that)",
        "#  DEMO of the light panel project (GENERATED by gen_light_panel.py --demo).\n"
        "#  Taps toggle tiles locally; nothing is sent anywhere useful. Test only.",
    )
    DEMO_OUT.parent.mkdir(parents=True, exist_ok=True)
    DEMO_OUT.write_text(demo, encoding="utf-8")
    print(f"written {DEMO_OUT}")
