# Built-in icon set for the light panel: 100 Material Design Icons (MDI 7.4.47)
# for a typical home. (group, [(mdi name, codepoint), ...]).
# Codepoints checked against the official MDI metadata when the set was made.
# To add one: find it at https://pictogrammers.com/library/mdi/ , add
# (name, codepoint) to a group, then re-run gen_light_panel.py.
ICON_SET = [
    ('Lights', [
        ('lightbulb', 'F0335'),
        ('lightbulb-outline', 'F0336'),
        ('lightbulb-group', 'F1253'),
        ('lightbulb-night', 'F1A4C'),
        ('ceiling-light', 'F0769'),
        ('ceiling-light-multiple', 'F18DD'),
        ('light-recessed', 'F179B'),
        ('chandelier', 'F1793'),
        ('floor-lamp', 'F08DD'),
        ('desk-lamp', 'F095F'),
        ('lamp', 'F06B5'),
        ('lamps', 'F1576'),
        ('wall-sconce', 'F091C'),
        ('led-strip-variant', 'F1051'),
        ('string-lights', 'F12BA'),
        ('spotlight-beam', 'F04C9'),
        ('track-light', 'F0914'),
        ('outdoor-lamp', 'F1054'),
        ('coach-lamp', 'F1020'),
    ]),
    ('Rooms and places', [
        ('home', 'F02DC'),
        ('sofa', 'F04B9'),
        ('bed', 'F02E3'),
        ('bed-king', 'F0FD2'),
        ('desk', 'F1239'),
        ('table-chair', 'F1061'),
        ('silverware-fork-knife', 'F0A70'),
        ('stove', 'F04DE'),
        ('bathtub', 'F1818'),
        ('shower', 'F09A0'),
        ('toilet', 'F09AB'),
        ('stairs', 'F04CD'),
        ('door', 'F081A'),
        ('door-open', 'F081C'),
        ('garage', 'F06D9'),
        ('gate', 'F0299'),
        ('fence', 'F179A'),
        ('balcony', 'F1817'),
        ('greenhouse', 'F002D'),
        ('tree', 'F0531'),
        ('flower', 'F024A'),
        ('grass', 'F1510'),
        ('pool', 'F0606'),
    ]),
    ('Audio and TV', [
        ('speaker', 'F04C3'),
        ('speaker-wireless', 'F071F'),
        ('amplifier', 'F0030'),
        ('radio', 'F0439'),
        ('music', 'F075A'),
        ('headphones', 'F02CB'),
        ('television', 'F0502'),
        ('projector', 'F042E'),
        ('cast', 'F0118'),
        ('gamepad-variant', 'F0297'),
    ]),
    ('Heating and air', [
        ('fan', 'F0210'),
        ('ceiling-fan', 'F1797'),
        ('air-conditioner', 'F001B'),
        ('air-purifier', 'F0D44'),
        ('radiator', 'F0438'),
        ('fireplace', 'F0E2E'),
        ('fire', 'F0238'),
        ('thermometer', 'F050F'),
        ('snowflake', 'F0717'),
        ('water-boiler', 'F0F92'),
        ('blinds', 'F00AC'),
        ('curtains', 'F1846'),
        ('window-open-variant', 'F11DC'),
    ]),
    ('Appliances', [
        ('kettle', 'F05FA'),
        ('coffee-maker', 'F109F'),
        ('microwave', 'F0C99'),
        ('toaster-oven', 'F0CD3'),
        ('fridge', 'F0290'),
        ('dishwasher', 'F0AAC'),
        ('washing-machine', 'F072A'),
        ('tumble-dryer', 'F0917'),
        ('robot-vacuum', 'F070D'),
        ('hair-dryer', 'F10EF'),
        ('printer', 'F042A'),
    ]),
    ('Power and devices', [
        ('power', 'F0425'),
        ('power-plug', 'F06A5'),
        ('power-socket-uk', 'F07E8'),
        ('toggle-switch', 'F0521'),
        ('lightning-bolt', 'F140B'),
        ('solar-power', 'F0A72'),
        ('battery', 'F0079'),
        ('ev-station', 'F05F1'),
        ('car', 'F010B'),
        ('desktop-classic', 'F07C0'),
        ('laptop', 'F0322'),
        ('router-wireless', 'F0469'),
    ]),
    ('Security and misc', [
        ('shield-home', 'F068A'),
        ('lock', 'F033E'),
        ('cctv', 'F07AE'),
        ('doorbell', 'F12E6'),
        ('bell', 'F009A'),
        ('alarm-light', 'F078F'),
        ('sprinkler', 'F105F'),
        ('watering-can', 'F1481'),
        ('star', 'F04CE'),
        ('dog', 'F0A43'),
        ('cat', 'F011B'),
        ('weather-night', 'F0594'),
    ]),
]
